### ISSUE TITLE
Global installation of tools?

### ISSUE THREAD

**Issue by ocs7474505** [hpcugent/easybuild#123]
I want use easybuild to provide the compiled programs for all users on the server, i.e. I need a global installation. Easybuild prevents me from installing the programs as root, which is necessary for this step. Unfortunately it does not address this issue in the manual or FAQ. What is your recommendation?

**Comment by boegel** [comment]
First of all: welcome to EasyBuild, @ocs7474505!

EasyBuild indeed complains when it's being run as root, because it's a *very* bad idea to build and install random (scientific) software that is auto-downloaded from the web as root (see for example https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/issues/123).

A less evil approach is to use a dedicated install user (e.g. `easybuild`), and give that user the necessary permissions to install to a central location. That provides some isolation in case some Makefile/scripts does something horribly wrong.

Another option is to install to a separate shared filesystem, and simply mount that filesystem on the system(s) where the software should be available.

Let us know whether this helps.

**Comment by ocs7474505** [comment]
Thanks for the help! The first option makes perfect sense and can be achieved rather quick.
