### ISSUE TITLE
bootstrapping on SLES12 doesn't work

### ISSUE THREAD

**Issue by andreas-h** [hpcugent/easybuild#169]
hilboll@heron:~> cat /etc/SuSE-release 
    SUSE Linux Enterprise Server 12 (x86_64)
    VERSION = 12
    PATCHLEVEL = 0
    # This file is deprecated and will be removed in a future service pack or release.
    # Please check /etc/os-release for details about this release.

in stage 2 of the bootstrapping procedure I get

    easybuild.tools.build_log.EasyBuildError: "Don't know how to determine subversions for SLES 12"

**Comment by boegel** [comment]
This is already fixed in current develop, see https://github.com/hpcugent/easybuild-framework/pull/1412 .

If you're really keen on getting EasyBuild to work on this system, you can download the EasyBuild 2.4.0 tarballs for framework, easyblocks and easyconfigs, patch the framework sources with the changes from https://github.com/hpcugent/easybuild-framework/pull/1412, and then use the alternate bootstrap procedure where you supply the source tarballs rather than letting the bootstrap script pull them in from PyPI, see http://easybuild.readthedocs.org/en/latest/Installation.html#bootstrapping-using-supplied-source-tarballs .

In any case, support for bootstrapping on SLES12 should work 'out of the box' with the next release of EasyBuild (v2.4.1 or v2.5.0, not sure yet whether there will be a v2.4.1).

**Comment by boegel** [comment]
fix is going to be included in next EasyBuild release, so closing this
