### ISSUE TITLE
Errno 21 in write_file

### ISSUE THREAD

**Issue by grenville** [hpcugent/easybuild#224]
Hi

I'm new to easy build and am tryng to install udunits as a test case. I've added these lines to an easyconfig

source_urls = ['ftp://ftp.unidata.ucar.edu/pub/udunits/']
sources = [SOURCE_TAR_GZ]

but get

== 2016-05-31 14:53:47,479 build_log.py:152 ERROR Failed to write to /home/n02/n02/grenvill/.local/easybuild/sources/u/udunits/: [Errno 21] Is a directory: '/home/n02/n02/grenvill/.local/easybuild/sources/u/udunits/' (at easybuild/tools/filetools.py:162 in write_file)
== 2016-05-31 14:53:47,480 build_log.py:152 ERROR Unexpected error occurred when trying to download ftp://ftp.unidata.ucar.edu/pub/udunits/ to /home/n02/n02/grenvill/.local/easybuild/sources/u/udunits/: "Failed to write to /home/n02/n02/grenvill/.local/easybuild/sources/u/udunits/: [Errno 21] Is a directory: '/home/n02/n02/grenvill/.local/easybuild/sources/u/udunits/'" (at easybuild/tools/filetools.py:332 in download_file)

It appears that /filetools.py:162 does indeed try to write to a directory?

Please advise.

Best wishes

Grenville

**Comment by boegel** [comment]
@grenville can you provide some more details, i.e. a couple more lines of log info to provide context?

Also, please enable debug logging using the `--debug` switch.

**Comment by grenville** [comment]
Hi - I ran with --debug and attached the log file

[eb-log.txt](https://github.com/hpcugent/easybuild/files/291457/eb-log.txt)

**Comment by boegel** [comment]
@grenville can you provide the *full* log (from `/tmp`) rather than only the application log (see http://easybuild.readthedocs.io/en/latest/Logfiles.html for the distinction); I'm still missing information with the log you provided now (in particular, the full easyconfig file, which will be included in the full log)

**Comment by grenville** [comment]
ahh - here it is
[eb-log.txt](https://github.com/hpcugent/easybuild/files/291545/eb-log.txt)

**Comment by boegel** [comment]
@grenville It's not a bug, EasyBuild gets confused by the list of patches you're specifying, i.e. a single patch with an empty filename:

```python
patches = ['']
```

We should probably check for empty filenames being passed down to make the problem more clear, but you should either remove that line, or use `patches = []` instead (i.e. an empty list, which is also the default).

Two other remarks:

* `sanity_check_paths` can't just provide empty lists, EasyBuild will complain about that at a later stage
* we already have easyconfigs for `UDUNITS`, see https://github.com/hpcugent/easybuild-easyconfigs/tree/master/easybuild/easyconfigs/u/UDUNITS

We try to stick the the 'official' software, which may explain why you've missed these, but you can check using `eb --search udunits`, you should see the easyconfig files available for `UDUNITS` in the search result (i.e. `--search` is case-*in*sensitive).

Please close this issue if things are clear now.

**Comment by grenville** [comment]
Kenneth - thanks for your help.

I'll close this but note that EasyBuild documentation is a little sparse, for example I have no idea what sanity_check_paths should contain (doing so implies that I know somehting about where things will go when installed - but I don't).

Aslo, for example, the explanation of what sources are: "sources: list of source files (filenames only)" is not clear, especilly when the examples are of the form sources = ['hpl-2.0.tar.gz']

**Comment by boegel** [comment]
@grenville Any specific suggestions on making things clearer? We always value input/feedback from people new to EasyBuild (since we take things for granted or are just used to how things are).

Is the documentation at http://easybuild.readthedocs.io/en/latest/Writing_easyconfig_files.html#sanity-check w.r.t. `sanity_check_paths` insufficient?

How could we improve the documentation w.r.t. `sources`? Explain how to figure out what to specify there via the website of the project in the example?
