### ISSUE TITLE
eb java Java-1.7.0_80.eb   --robot  --experimental --rpath failure

### ISSUE THREAD

**Issue by EricDeveaud** [hpcugent/easybuild#281]
FYI 

after boostraping a fresh easybuild-3.0 to give a try to rpath support 

all eb installation was done using "--experimental --rpath" flags

particulary goolf-1.7.20 was installed using 
```
eb goolf-1.7.20.eb --robot -l --experimental --rpath
```
and then tried  installing R-3.2.0-goolf-1.7.20.eb
that fails on java-1.7_80 installation 

in order to minimize the log file size I issued following eb command
```
eb java Java-1.7.0_80.eb   --robot  --experimental --rpath
```
here is the output of the above command and attached the logfile.

```
bigmess:/soft/src > eb Java-1.7.0_80.eb   --robot  --experimental --rpath 
== temporary log file in case of crash /tmp/eb-p_laAD/easybuild-aPP5My.log
== resolving dependencies ...
== processing EasyBuild easyconfig /soft/adm/easybuild/software/EasyBuild/3.0.0/lib/python2.7/site-packages/easybuild_easyconfigs-3.0.0-py2.7.egg/easybuild/easyconfigs/j/Java/Java-1.7.0_80.eb
== building and installing Java/1.7.0_80...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== postprocessing...
== sanity checking...
== FAILED: Installation ended unsuccessfully (build directory: /home/edeveaud/.local/easybuild/build/Java/1.7.0_80/dummy-dummy): build failed (first 300 chars): Sanity check failed: No '(RPATH)' found in 'readelf -d' output for /soft/exe/Java/1.7.0_80/bin/javaws: 
Dynamic section at offset 0x1a3f0 contains 25 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libX11.so.6]
 0x00000000000000
== Results of the build can be found in the log file(s) /tmp/eb-p_laAD/easybuild-Java-1.7.0_80-20161123.115520.vaRxW.log
ERROR: Build of /soft/adm/easybuild/software/EasyBuild/3.0.0/lib/python2.7/site-packages/easybuild_easyconfigs-3.0.0-py2.7.egg/easybuild/easyconfigs/j/Java/Java-1.7.0_80.eb failed (err: "build failed (first 300 chars): Sanity check failed: No '(RPATH)' found in 'readelf -d' output for /soft/exe/Java/1.7.0_80/bin/javaws: \nDynamic section at offset 0x1a3f0 contains 25 entries:\n  Tag        Type                         Name/Value\n 0x0000000000000001 (NEEDED)             Shared library: [libX11.so.6]\n 0x00000000000000")

```

best regards

Eric

[easybuild-aPP5My.log.txt](https://github.com/hpcugent/easybuild/files/608659/easybuild-aPP5My.log.txt)

**Comment by boegel** [comment]
@EricDeveaud please report problems with the RPATH support in the `easybuild-framework` repository (via https://github.com/hpcugent/easybuild-framework/issues/new), since that's also where the codebase for the core of EasyBuild resides

This seems like a case of a known issue with the current RPATH support, i.e. that the RPATH sanity check is always run when `--rpath` is used, even for binary installations where nothing gets built/linked via EasyBuild (see the 1st bullet at https://github.com/hpcugent/easybuild-framework/issues/1992).

We'll need to put some logic in place to somehow filter out binaries/libraries that were not built during the installation process. One option would be to specialise the `sanity_check_rpath` method  in the `Binary` generic easyblock to basically just do a `pass`, but I suspect more will be needed (e.g. also in `IntelBase` and some software-specific easyblocks for binary installations).

Are you up for taking a stab at that?

**Comment by EricDeveaud** [comment]
without guarantee, as I'm quite busy. I'll take a llok at sanity check

**Comment by boegel** [comment]
@EricDeveaud I suggest we follow this up via https://github.com/hpcugent/easybuild-framework/issues/2039?

**Comment by boegel** [comment]
fixed with https://github.com/hpcugent/easybuild-easyblocks/pull/1056
