### ISSUE TITLE
Python 2 & 3 co-exsitence

### ISSUE THREAD

**Issue by koallen** [hpcugent/easybuild#323]
Hi,

I installed both Python 2 and 3 with the foss 2016b toolchain. However, they are all under "Python" and thus causing conflict. Why are they made to be conflicting with each other? Shouldn't they co-exist without any problem? (assuming `python2` and `python3` is used to remove ambiguity)

**Comment by boegel** [comment]
In some use cases, it makes sense to have both Python 2 & 3 active in the same session, in others it doesn't.

The default for Python installations performed with EasyBuild is to not mix Python 2 & 3 since you may run into problems when you install additional modules that use Python on top, i.e. stuff that is installed with Python 2 would not be available when using `python3` and vice versa, or worse, may get loaded but be broken.

That being said, you can change the Python easyconfigs to rename the generated module to `Python2/...` and `Python3/...`, so you can use both at the same time in a session.

Adding a line like this to the Python easyconfig file should do the trick:

```python
modaltsoftname = 'Python%(version_major)s'
```

Do let us know if this answers your question (and if so, please close this issue).

**Comment by koallen** [comment]
Thanks for the explanation and the tip! I guess that what I'll do!
