### ISSUE TITLE
--confighelp generates job-* options incorrectly

### ISSUE THREAD

**Issue by pol** [hpcugent/easybuild#329]
When generating a sample config file, there are two issues:

1. the `[job]` section lists the options as `job-<option>`, which causes the option loader to interpret each of these options as `job-job-<option>`.  

For example, the `backend-config` option is output as: `job-backend-config` in the `[job]` section.  When setting it (and uncommenting it), easybuild throws this error: `ERROR: Failed to parse configuration options: 'parseconfigfiles: no option corresponding with opt job-backend-config dest job_job_backend_config in section job'`.  Modifying the config file and changing `job-backend-config` to `backend-config` fixes the problem.  The `job-` prefix for options in the `[job]` section should not be there.

2. The `job-backend` option is in the `[config]` section instead of in the `[job]` section.  This isn't causing any breakage, but is potentially confusing.

**Comment by boegel** [comment]
Thanks for reporting this @pol.

This is (mostly?) a duplicate of https://github.com/hpcugent/easybuild-framework/issues/1331, and it should be fixed in `vsc-base`, cfr. https://github.com/hpcugent/vsc-base/issues/211

`job-backend` in the `config` section is kind of deliberate, since it's a general configuration parameter, rather than something specific to the jobs being submitted... I agree it's potentially confusing though.

**Comment by pol** [comment]
I agree that this is essentially the same issue.  I shall close it.
